name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  desktopTest:
    strategy:
      matrix:
        os: [macos]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew :noko:desktopJar

    - name: Test
      run: ./gradlew :noko:desktopTest

    - name: Upload html reports
      uses: actions/upload-artifact@v2.3.1
      if: always()
      with:
        name: desktopTest-${{ matrix.os }}-reports.zip
        path: ./noko/build/reports/tests/desktopTest

    # - name: Publish Unit Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@v1
    #   if: always()
    #   with:
    #     files: ./noko/build/test-results/**/*.xml